server.port=8081

telegram.bot.token=secretik

spring.datasource.url=jdbc:postgresql://localhost:5432/notification
spring.datasource.username=secretik
spring.datasource.password=secretik

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.change-log=classpath:liquibase/scripts/script.sql

spring.task.scheduling.pool.size=2

logging.level.pro.sky.telegrambot.service=DEBUG
